### PR TITLE
web frontend: redesign

### PR DESCRIPTION
**Pull request by riotbib**
i added a HTML meta tag for mobile users. this PR enhances the experience for smartphone and tablet users.

@oxzi, please review, and possibly merge and deploy. thank you.

### CODE REVIEW

**Comment by oxzi** [comment]
Thanks a lot for your PR!

However, this results in the headline to break into two lines including the indentation. I attached two screenshots, one with and one without your patch.

Unfortunately, I can't get my CSS foo to work at this hour. Do you like to look again please?

Without the patch:

With the patch applied:

**Comment by riotbib** [comment]
@oxzi, as you may see with the new push, `<h1>` is now flowting to the right and there is one special rule for mobile users. please review again.

**Comment by riotbib** [comment]
commit https://github.com/oxzi/bbb-broadcaster/pull/1/commits/4568bfaa83ae2bed35edf1445fb19651ee4e0b4d adds an info box with helpful information.

**Review by oxzi — APPROVED** [review]
Looks good to me, thanks a lot!

**Pull request merged**
